server:
  port: 9120
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=UTC&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: oauth
    password: 123456
#spring:
#  security:
#    user:
#      name: user
#      password: user
